- name: Install Redis Repo
  ansible.builtin.shell: dnf install https://rpms.remirepo.net/enterprise/remi-release-8.rpm --nobest --skip-broken -y

- name: Enable Redis Module
  ansible.builtin.shell: dnf module enable redis:6 -y

- name: INstall Redis
  ansible.builtin.yum:
    name: redis
    state: installed

- name: Update Listen address /etc/redis.conf
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Update Listen address /etc/redis/redis.conf
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start Redis
  ansible.builtin.systemd:
    name: redis
    state: restarted
    enabled: yes