- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Copy RoboShop Configuration
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Copy Nginx Configuration - Main Config
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Clean Old content
  ansible.builtin.shell: rm -rf /usr/share/nginx/html/*

#- name: Download Application Content
#  ansible.builtin.unarchive:
#    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
#    dest: /usr/share/nginx/html
#    remote_src: yes

- name: Download Application Content From Nexus Repo
  ansible.builtin.unarchive:
    src: http://{{ nexus_username }}:{{ nexus_password }}@nexus.rsdevops.in/repository/{{ component }}/{{ component }}-{{ version }}.zip
    dest: /usr/share/nginx/html
    remote_src: yes
  vars:
    nexus_username: "{{ lookup('amazon.aws.aws_ssm', 'nexus.{{ env }}.username', region='us-east-1') }}"
    nexus_password: "{{ lookup('amazon.aws.aws_ssm', 'nexus.{{ env }}.password', region='us-east-1') }}"
    version: "{{ lookup('amazon.aws.aws_ssm', component ~ '.version', region='us-east-1') }}"

- name: Install Node Exporter
  ansible.builtin.import_role:
    name: common
    tasks_from: node-exporter.yml

#- name: Setup Rsyslog Configuration file
#  ansible.builtin.template:
#    src: "rsyslog.conf"
#    dest: /etc/rsyslog.d/roboshop.conf
#
#- name: Start rsyslog Service
#  ansible.builtin.systemd:
#    name: "rsyslog"
#    state: restarted

- name: Start {{ component }} Service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes

- name: Setup Filebeat
  ansible.builtin.import_role:
    name: elk
    tasks_from: filebeat.yml