- name: Copy {{ component }} Service
  ansible.builtin.template:
    src: "{{ component }}.service"
    dest: "/etc/systemd/system/{{ component }}.service"

- name: Copy MongoDB Repo
  ansible.builtin.template:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo
    when: "{{ component }} is catalogue"

- name: Create RoboShop User
  ansible.builtin.shell: useradd roboshop

- name: Cleanup Existing Application Content
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create Application Directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download {{ component }} Artifacts
  ansible.built.unarchive:
    src: "https://roboshop-artifacts.s3.amazonaws.com/{{ component }}.zip"
    dest: "/tmp/{{ component }}.zip"
    remote_src: yes