- name: Copy {{ component }} Service
  ansible.builtin.template:
    src: "{{ component }}.service"
    dest: "/etc/systemd/system/{{ component }}.service"

- name: Copy MongoDB Repo
  ansible.builtin.template:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo
  when: component == "catalogue" or component == "user"

- name: Add Application User
  ansible.builtin.user:
    name: roboshop

- name: Cleanup Existing Application Content
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create Application Directory
  ansible.builtin.file:
    path: /app
    state: directory

#- name: Download {{ component }} Artifacts
#  ansible.builtin.unarchive:
#    src: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}.zip
#    dest: /app
#    remote_src: yes

- name: Download {{ component }} Artifacts
  ansible.builtin.unarchive:
    src: http://{{ nexus_username }}:{{ nexus_password }}@nexus.rsdevops.in/repository/{{ component }}/{{ component }}-{{ version }}.zip
    dest: /app
    remote_src: yes
  vars:
    nexus_username: "{{ lookup('amazon.aws.aws_ssm', 'nexus.{{ env }}.username', region='us-east-1') }}"
    nexus_password: "{{ lookup('amazon.aws.aws_ssm', 'nexus.{{ env }}.password', region='us-east-1') }}"
    version: "{{ lookup('amazon.aws.aws_ssm', component ~ '.{{ env }}.version', region='us-east-1') }}"

- name: Setup Rsyslog Configuration file
  ansible.builtin.template:
    src: "rsyslog.conf"
    dest: /etc/rsyslog.d/roboshop.conf

- name: Start rsyslog Service
  ansible.builtin.systemd:
    name: "rsyslog"
    state: restarted