- name: Install Java
  ansible.builtin.yum:
    name: maven
    state: installed

- name: App prerequisites
  ansible.builtin.import_tasks: appreq.yml

- name: Install Dependencies
  ansible.builtin.shell: mvn clean package; mv target/shipping-1.0.jar shipping.jar
  args:
    chdir: /app

- name: Load Schema
  ansible.builtin.import_tasks: mongo-schema.yml
  when: schema is defined

- name: Start {{component}} Service
  ansible.builtin.import_tasks: systemd-setup.yml