- name: Install MongoDB Client
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

- name: Download DocumentDB pem file
  ansible.builtin.get_url:
    url: https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem
    dest: /app/rds-combined-ca-bundle.pem

- name: Load Schema
  ansible.builtin.shell: mongo --tls --host dev-docdb-cluster.cluster-c0104uc8qq16.us-east-1.docdb.amazonaws.com:27017 --tlsCAFile /app/rds-combined-ca-bundle.pem --username docdbadmin --password roboshop1234 </app/schema/{{component}}.js