- name: Install MongoDB Client
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

- name: Load Schema
  ansible.builtin.shell: mongo --ssl --host dev-docdb-cluster.cluster-c0104uc8qq16.us-east-1.docdb.amazonaws.com:27017 --sslCAFile /app/rds-combined-ca-bundle.pem --username docdbadmin --password roboshop1234 </app/schema/{{component}}.js