- name: Install MySQL Client
  ansible.builtin.yum:
    name: mysql
    state: installed

- name: Load Schema
  ansible.builtin.shell: mysql -h dev-rds-cluster.cluster-c0104uc8qq16.us-east-1.rds.amazonaws.com -udevadmin -proboshop1234 < /app/schema/{{component}}.sql