- name: Download Node Exporter Binary
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v1.9.0/node_exporter-1.9.0.linux-amd64.tar.gz"
    dest: "/tmp/node_exporter-1.9.0.linux-amd64.tar.gz"

- name: Extract Node Exporter
  ansible.builtin.unarchive:
    src: "/tmp/node_exporter-1.9.0.linux-amd64.tar.gz"
    dest: "/tmp/"
    remote_src: yes

- name: Move Node Exporter Binary
  ansible.builtin.shell: mv /tmp/node_exporter-1.9.0.linux-amd64/node_exporter /usr/local/bin/

- name: Create A Node Exporter User
  ansible.builtin.user:
    name: node_exporter
    shell: /bin/false
    system: yes

- name: Copy Node Exporter Service File
  ansible.builtin.template:
    src: node_exporter.service
    dest: /etc/systemd/system/

- name: Start Node Exporter Service
  ansible.builtin.systemd:
    name: node_exporter
    state: restarted
    enabled: yes
    daemon_reload: yes
