- name: INstall NodeJS Repos
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install NodeJS
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: App prerequisites
  ansible.builtin.import_tasks: appreq.yml

- name: Install Dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: Load Schema
  ansible.builtin.import_tasks: mongo-schema.yml
  when: "{{ component }}" is catalogue

- name: Start {{component}} Service
  ansible.builtin.import_tasks: systemd-setup.yml