- name: Install Python
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: App prerequisites
  ansible.builtin.import_tasks: appreq.yml

- name: Install Dependencies
  ansible.builtin.shell: pip3.6 install -r requirements.txt
  args:
    chdir: /app

- name: Start {{component}} Service
  ansible.builtin.import_tasks: systemd-setup.yml